# Application Name
spring.application.name=profile

# Server Port
server.port=8080

# --- MySQL Database Configuration ---

# Hibernate settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Database Connection using Kubernetes environment variables
# These variables (MYSQL_DB_HOST, MYSQL_DB_PORT, etc.) will be injected via ConfigMap and Secret later.
spring.datasource.url=jdbc:mysql://${MYSQL_DB_HOST}:${MYSQL_DB_PORT}/test?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${MYSQL_DB_USERNAME}
spring.datasource.password=${MYSQL_DB_PASSWORD}

# Explicitly specify the MySQL driver class
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
