apiVersion: v1
kind: Secret
metadata:
  name: profile-secret
type: Opaque
data:
  mysql-username: {{ .Values.mysql.profile.username | b64enc | quote }}
  mysql-password: {{ .Values.mysql.profile.password | b64enc | quote }}
