# TODO: Implement the secret for chat service
{{- if eq .Values.global.environment "gcp" }}
apiVersion: v1
kind: Secret
metadata:
  name: chat-secret
type: Opaque
data:
  mysql-username: cm9vdA==
  mysql-password: eW91cl9zZWN1cmVfcGFzc3dvcmQ=
{{- end }}
