apiVersion: v1
kind: Secret
metadata:
  name: login-secret
type: Opaque
data:
  mysql-username: {{ .Values.mysql.login.username | b64enc | quote }}
  mysql-password: {{ .Values.mysql.login.password | b64enc | quote }}
